### ISSUE TITLE
Migrate Yelp API v3 updates from premium to free plugin

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Yelp-Widget-Pro#2]
## Issue Overview

Yelp Widget Premium was recently updated to Yelp API v3. The free version of the plugin on wp.org could benefit from these updates as well.

## Tasks

- [x] Replace v2 requests with v3 requests.
- [x] Add settings fields.
- [x] Add instructions.
- [x] Add backup key.
- [x] Add star images.
- [x] Add new logo.
